# Generated by Django 2.0.6 on 2018-11-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepthOfKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('tgPage', models.CharField(blank=True, max_length=255)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('dok', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('master', models.CharField(max_length=200)),
                ('unionedkey', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.CharField(default='default', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('PrerequisiteLesson3', models.CharField(blank=True, max_length=255)),
                ('PrerequisiteLesson2', models.CharField(blank=True, max_length=255)),
                ('PrerequisiteLesson1', models.CharField(blank=True, max_length=255)),
                ('FutureLesson1', models.CharField(blank=True, max_length=255)),
                ('FutureLesson2', models.CharField(blank=True, max_length=255)),
                ('FutureLesson3', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentActivity',
            fields=[
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='EA', serialize=False, to='master.Master')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lesson', serialize=False, to='master.Master')),
                ('lesson', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolForInstruction',
            fields=[
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tool', serialize=False, to='master.Master')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='progression',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Progression', to='master.Master'),
        ),
        migrations.AddField(
            model_name='progression',
            name='unionkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Progression', to='master.Lesson'),
        ),
        migrations.AddField(
            model_name='depthofknowledge',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepthOfKnowledge', to='master.Master'),
        ),
        migrations.AddField(
            model_name='depthofknowledge',
            name='unionkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepthOfKnowledge', to='master.Lesson'),
        ),
    ]
