# Generated by Django 2.0.6 on 2018-11-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichmentactivity',
            name='master',
        ),
        migrations.DeleteModel(
            name='EnrichmentActivity',
        ),
    ]
