# Generated by Django 2.0.6 on 2018-11-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20181107_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonname',
            name='master',
        ),
        migrations.DeleteModel(
            name='LessonName',
        ),
    ]
