# Generated by Django 2.0.6 on 2018-11-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20181107_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('activitySheetName', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivitySheet', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivitySheet', to='master.Lesson')),
            ],
        ),
    ]
