# Generated by Django 2.0.6 on 2018-11-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_activitysheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('component', models.CharField(blank=True, max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('itemType', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssessmentItemType', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssessmentItemType', to='master.Lesson')),
            ],
        ),
    ]
