# Generated by Django 2.0.6 on 2018-11-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_assessmentitemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depthofknowledge',
            old_name='item',
            new_name='dokitem',
        ),
    ]
