# Generated by Django 2.0.6 on 2018-12-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_contentobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('context', models.CharField(blank=True, max_length=255)),
                ('issues', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contexts', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contexts', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CrossCurricularConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('component', models.CharField(blank=True, max_length=255)),
                ('contentArea', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossCurricularConnections', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossCurricularConnections', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('baseTenBlocksTool', models.CharField(blank=True, max_length=255)),
                ('perimeterAndAreaTool', models.CharField(blank=True, max_length=255)),
                ('fractionModelsTool', models.CharField(blank=True, max_length=255)),
                ('numberLineTool', models.CharField(blank=True, max_length=255)),
                ('multiplicationModelsTool', models.CharField(blank=True, max_length=255)),
                ('countersConnectingCubesTool', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DigitalTools', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DigitalTools', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('EnrichmentActivityGrade', models.CharField(blank=True, max_length=255)),
                ('EnrichmentActivityLesson', models.CharField(blank=True, max_length=255)),
                ('FileName', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnrichmentActivities', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnrichmentActivities', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='EthnicityGenderAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('ethnicity', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('ability', models.CharField(blank=True, max_length=255)),
                ('correctOrIncorrect', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EthnicityGenderAbility', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EthnicityGenderAbility', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='FluencyActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('fluencyPracticeTitle', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FluencyActivities', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FluencyActivities', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicOrganizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('graphicOrganizer', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GraphicOrganizers', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GraphicOrganizers', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('interactiveTutorial', models.CharField(blank=True, max_length=255)),
                ('videoID', models.CharField(blank=True, max_length=255)),
                ('objective', models.CharField(blank=True, max_length=255)),
                ('estimatedTime', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractiveTutorial', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractiveTutorial', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('languageObjective', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguageObjectives', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguageObjectives', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LearningGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('learningGame', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LearningGames', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LearningGames', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgressionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('previousLearning', models.CharField(blank=True, max_length=255)),
                ('inThisLesson', models.CharField(blank=True, max_length=255)),
                ('subsequentLearning', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LearningProgressionText', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LearningProgressionText', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('lessonName', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LessonNames', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LessonNames', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Manipulatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('manipulativeUsed', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('use', models.CharField(blank=True, max_length=255)),
                ('required', models.CharField(blank=True, max_length=255)),
                ('lesson', models.CharField(blank=True, max_length=255)),
                ('activities', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manipulatives', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manipulatives', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='MathCenterActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MathCenterActivities', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MathCenterActivities', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('model', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Models', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Models', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteInteractiveTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('prerequisiteInteractiveTutorial', models.CharField(blank=True, max_length=255)),
                ('prerequisiteVideoID', models.CharField(blank=True, max_length=255)),
                ('prerequisiteObjective', models.CharField(blank=True, max_length=255)),
                ('prerequisiteEstimatedTime', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteInteractiveTutorial', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteInteractiveTutorial', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('prerequisiteLessonGrade', models.CharField(blank=True, max_length=255)),
                ('prerequisiteLessonNumber', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteLessons', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteLessons', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('prerequisiteSkill', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteSkill', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrerequisiteSkill', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('typeOfRubric', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rubrics', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rubrics', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SMPsInLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('SMP', models.CharField(blank=True, max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('typeOfRubric', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SMPsInLessons', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SMPsInLessons', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsforInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('toolForInstruction', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToolsforInstruction', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToolsforInstruction', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='VisualModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('pagewithVisualModel', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VisualModels', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VisualModels', to='master.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField()),
                ('academic', models.CharField(blank=True, max_length=255)),
                ('vocabularyTerm', models.CharField(blank=True, max_length=255)),
                ('definition', models.CharField(blank=True, max_length=255)),
                ('newOrReview', models.CharField(blank=True, max_length=255)),
                ('vocabularyBoxPage', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vocabulary', to='master.Master')),
                ('unionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vocabulary', to='master.Lesson')),
            ],
        ),
        migrations.RenameField(
            model_name='contentobjective',
            old_name='contentobjective',
            new_name='contentObjective',
        ),
    ]
