# Generated by Django 2.0.6 on 2019-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20190201_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
