# Generated by Django 2.0.6 on 2019-03-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20190306_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
