# Generated by Django 2.0.6 on 2019-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20190306_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
