# Generated by Django 2.0.6 on 2019-03-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20190311_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardcodesandverbiage',
            name='id',
        ),
        migrations.AlterField(
            model_name='standardcodesandverbiage',
            name='standard',
            field=models.CharField(default='default', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardsinlessons',
            name='standardCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StandardInLessons', to='master.StandardCodesAndVerbiage'),
        ),
    ]
