# Generated by Django 2.0.6 on 2019-03-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20190312_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardsinlessons',
            name='standardCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StandardInLessons', to='master.StandardCodesAndVerbiage'),
        ),
    ]
