# Generated by Django 2.0.6 on 2019-03-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_auto_20190312_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsinlessons',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StandardInLessons', to='master.StandardCodesAndVerbiage'),
        ),
        migrations.AlterField(
            model_name='standardsinlessons',
            name='standardCode',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
