# Generated by Django 2.0.6 on 2019-04-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20190312_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionList', models.TextField(blank=True)),
                ('gradeList', models.TextField(blank=True)),
                ('unitList', models.TextField(blank=True)),
                ('lessonList', models.TextField(blank=True)),
            ],
        ),
    ]
