# Generated by Django 2.0.6 on 2019-04-05 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_duplicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicationlog',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
