# Generated by Django 2.0.6 on 2019-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_duplicationlog_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivetutorial',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningprogressiontext',
            name='inThisLesson',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningprogressiontext',
            name='previousLearning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningprogressiontext',
            name='subsequentLearning',
            field=models.TextField(blank=True),
        ),
    ]
