# Generated by Django 2.0.6 on 2019-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_duplicationlog_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
