# Generated by Django 2.0.6 on 2019-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20190421_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisiteinteractivetutorial',
            name='prerequisiteObjective',
            field=models.TextField(blank=True),
        ),
    ]
