# Generated by Django 2.0.6 on 2019-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20190506_1538'),
        ('master', '0023_auto_20190422_1020'),
    ]

    operations = [
    ]
