# Generated by Django 2.0.6 on 2019-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_merge_20190513_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichmentactivities',
            old_name='FileName',
            new_name='fileName',
        ),
        migrations.RemoveField(
            model_name='enrichmentactivities',
            name='EnrichmentActivityGrade',
        ),
        migrations.RemoveField(
            model_name='enrichmentactivities',
            name='EnrichmentActivityLesson',
        ),
        migrations.AddField(
            model_name='enrichmentactivities',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
