# Generated by Django 2.0.6 on 2019-06-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_academicvocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardsinlessons',
            name='standard',
        ),
        migrations.DeleteModel(
            name='StandardCodesAndVerbiage',
        ),
    ]
