# Generated by Django 2.0.6 on 2019-06-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_auto_20190628_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCodesAndVerbiage',
            fields=[
                ('code', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('standard', models.CharField(blank=True, max_length=255)),
                ('standardVersion', models.CharField(blank=True, max_length=255)),
                ('standardWording', models.TextField(blank=True)),
                ('majorSuportingOrAdditional', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='standardsinlessons',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StandardInLessons', to='master.StandardCodesAndVerbiage'),
        ),
    ]
