# Generated by Django 2.0.6 on 2019-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_auto_20190628_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMPText',
            fields=[
                ('code', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('smp', models.CharField(blank=True, max_length=255)),
                ('SMPText', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='smpsinlessons',
            name='master',
        ),
        migrations.RemoveField(
            model_name='smpsinlessons',
            name='unionkey',
        ),
        migrations.DeleteModel(
            name='SMPsInLessons',
        ),
    ]
