# Generated by Django 2.0.6 on 2019-06-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_smpsinlessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smpsinlessons',
            name='SMP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SMPsInLessons', to='master.SMPText'),
        ),
    ]
